language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pandreidoru/dockers_web_fibonacci/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true pandreidoru/dockers_web_fibonacci/react-test npm test

after_success:
  - docker build -t pandreidoru/dockers_web_fibonacci-client ./client
  - docker build -t pandreidoru/dockers_web_fibonacci-nginx ./nginx
  - docker build -t pandreidoru/dockers_web_fibonacci-server ./server
  - docker build -t pandreidoru/dockers_web_fibonacci-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push docker images to docker hub
  - docker push pandreidoru/dockers_web_fibonacci-client
  - docker push pandreidoru/dockers_web_fibonacci-nginx
  - docker push pandreidoru/dockers_web_fibonacci-server
  - docker push pandreidoru/dockers_web_fibonacci-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: dockers_web_fibonacci
  env: DockersWebFibonacci-env
  bucket-name: elasticbeanstalk-us-east-2-802438180470
  bucket_path: docker-multi
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY